projects:
  app:
    schemaPath: "prisma/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  db:
    schemaPath: "prisma/generated/schema.graphqls"
    extensions:
      endpoints:
        default: "http://localhost:4466"
      prisma: prisma/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts