version: '3'

services:
  eureka:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8761:8761'
    working_dir: /eureka-server
    volumes:
      - ./eureka-server:/eureka-server
    depends_on:
      - prisma
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8080:8080'
    working_dir: /api-gateway
    volumes:
      - ./api-gateway:/api-gateway
    depends_on:
      - prisma
      - eureka
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
  postgres:
    image: postgres:9.5-alpine
    restart: always
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=caseyrharding
    volumes:
    - postgres:/var/lib/postgresql/data
  prisma:
    image: prismagraphql/prisma:1.8
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: caseyrharding
            password: password
            migrations: true
  users-api:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8085:8085'
    working_dir: /users-api
    volumes:
      - ./users-api:/users-api
    depends_on:
      - prisma
      - eureka
    command: './gradlew bootRun'
    environment:
      - GRADLE_USER_HOME=cache
      - SPRING_PROFILES_ACTIVE=dev
volumes:
  postgres:





#  comments-api:
#    image: anapsix/alpine-java:8_jdk_unlimited
#    ports:
#      - '8082:8082'
#    working_dir: /comments-api
#    volumes:
#      - ./comments-api:/comments-api
#    depends_on:
#      - postgresdev
#      - eureka
#    command: './gradlew bootRun'
#    environment:
#      - GRADLE_USER_HOME=cache
#      - SPRING_PROFILES_ACTIVE=dev
#  friends-api:
#    image: anapsix/alpine-java:8_jdk_unlimited
#    ports:
#      - '8083:8083'
#    working_dir: /friends-api
#    volumes:
#      - ./friends-api:/friends-api
#    depends_on:
#      - postgresdev
#      - eureka
#    command: './gradlew bootRun'
#    environment:
#      - GRADLE_USER_HOME=cache
#      - SPRING_PROFILES_ACTIVE=dev
#  posts-api:
#    image: anapsix/alpine-java:8_jdk_unlimited
#    ports:
#      - '8084:8084'
#    working_dir: /posts-api
#    volumes:
#      - ./posts-api:/posts-api
#    depends_on:
#      - postgresdev
#      - eureka
#    command: './gradlew bootRun'
#    environment:
#      - GRADLE_USER_HOME=cache
#      - SPRING_PROFILES_ACTIVE=dev