DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS FRIENDS;
DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS COMMENTS;

create table USERS (
    ID SERIAL,
    USERNAME varchar(100) NOT NULL UNIQUE,
    FIRST_NAME varchar(100),
    LAST_NAME varchar(100),
    EMAIL varchar(100),
    LOCATION varchar(100),
    ABOUT_ME varchar(500),
    PASSWORD varchar(100),
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

create table FRIENDS (
    ID SERIAL PRIMARY KEY,
    STATUS integer,
    FRIEND_SENT_REQUEST integer,
    FRIEND_RECEIVED_REQUEST integer,
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP,
    CONSTRAINT FRIEND_SENT_REQUEST FOREIGN KEY(FRIEND_SENT_REQUEST)
        REFERENCES USERS (ID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT FRIEND_RECEIVED_REQUEST FOREIGN KEY(FRIEND_RECEIVED_REQUEST)
        REFERENCES USERS (ID)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

create table POSTS (
    ID SERIAL PRIMARY KEY,
    TITLE varchar(50),
    POSTER_ID integer,
    POST_TEXT varchar(500),
    NUMBER_OF_LIKES integer DEFAULT 0,
    NUMBER_OF_COMMENTS integer DEFAULT 0,
    ABLE_TO_VIEW integer DEFAULT 0,
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP,
    CONSTRAINT POSTER_ID FOREIGN KEY(POSTER_ID)
        REFERENCES USERS (ID)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

create table COMMENTS (
    ID SERIAL PRIMARY KEY,
    COMMENTER_ID integer,
    POST_ID integer,
    COMMENT_TEXT varchar(500),
    NUMBER_OF_LIKES integer DEFAULT 0,
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP,
    CONSTRAINT COMMENTER_ID FOREIGN KEY(COMMENTER_ID)
        REFERENCES USERS (ID)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT POST_ID FOREIGN KEY(POST_ID)
        REFERENCES POSTS (ID)
        ON UPDATE RESTRICT ON DELETE CASCADE
)