--DROP TABLE IF EXISTS USERS;
--DROP TABLE IF EXISTS FRIENDS;
--DROP TABLE IF EXISTS POSTS;
--DROP TABLE IF EXISTS COMMENTS;

create table USERS (
    ID SERIAL,
    USERNAME varchar(100) NOT NULL UNIQUE,
    FIRST_NAME varchar(100),
    LAST_NAME varchar(100),
    EMAIL varchar(100),
    LOCATION varchar(100),
    ABOUT_ME varchar(500),
    PASSWORD varchar(100),
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP
);

create table FRIENDS (
    ID SERIAL PRIMARY KEY,
    STATUS integer,
    FRIEND_SENT_REQUEST integer,
    FRIEND_RECEIVED_REQUEST integer,
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP
);

create table COMMENTS (
    ID SERIAL PRIMARY KEY,
    COMMENTER_ID integer,
    POST_ID integer,
    COMMENT_TEXT varchar(500),
    NUMBER_OF_LIKES integer DEFAULT 0,
    TIME_ADDED TIMESTAMP default CURRENT_TIMESTAMP
);